const SGDS_RUNTIME_STRATEGY_ = 'APPS_SCRIPT_FIRST_NO_BILLING';
const SGDS_PRIMARY_WORKER_ = 'GOOGLE_APPS_SCRIPT';
const SGDS_FILE_STORE_ = 'GOOGLE_DRIVE';
const SGDS_BUSINESS_LEDGER_ = 'GOOGLE_SHEETS';
const SGDS_CONTROL_PLANE_ = 'FIRESTORE';
const SGDS_FRONTEND_ = 'FIREBASE_HOSTING_STATIC';
const SGDS_AUTHENTICATION_ = 'FIREBASE_AUTH_GOOGLE';
const SGDS_BILLING_REQUIRED_ = 'NO';
const SGDS_CLOUD_RUN_STATUS_ = 'DEFERRED_OPTIONAL';
const SGDS_CLOUD_RUN_PRIMARY_PATH_ = 'NO';
const SGDS_CLOUD_RUN_BLOCKER_FOR_CURRENT_ROADMAP_ = 'NO';

function getSgdsRuntimeArchitectureDecision_() {
  return Object.freeze({
    SGDS_RUNTIME_STRATEGY: SGDS_RUNTIME_STRATEGY_,
    PRIMARY_WORKER: SGDS_PRIMARY_WORKER_,
    FILE_STORE: SGDS_FILE_STORE_,
    BUSINESS_LEDGER: SGDS_BUSINESS_LEDGER_,
    CONTROL_PLANE: SGDS_CONTROL_PLANE_,
    FRONTEND: SGDS_FRONTEND_,
    AUTHENTICATION: SGDS_AUTHENTICATION_,
    BILLING_REQUIRED: SGDS_BILLING_REQUIRED_,
    CLOUD_RUN_STATUS: SGDS_CLOUD_RUN_STATUS_,
    CLOUD_RUN_PRIMARY_PATH: SGDS_CLOUD_RUN_PRIMARY_PATH_,
    CLOUD_RUN_BLOCKER_FOR_CURRENT_ROADMAP: SGDS_CLOUD_RUN_BLOCKER_FOR_CURRENT_ROADMAP_,
    CLOUD_RUN_CODE_RETAINED: 'YES_OPTIONAL_ADAPTER'
  });
}
